baseURL = "https://josephname.github.io/joename/"
languageCode = 'en-us'
title = 'JOENAME dot COM'
theme = "hugo-coder"

# Author information
[author]
  name = "Joe Name"
  bio = "Infrastructure enthusiast. Sharing ideas and projects." # Optional

# Main menu configuration
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2

[[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight =3
